apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # External port for frontend
      targetPort: 3000  # Frontend container port
  type: LoadBalancer  # Expose frontend as a public service
