apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80  # External port for backend
      targetPort: 3001  # Backend container port
  type: LoadBalancer  # Expose backend as a public service
